version: 2.1

jobs:
  deploy-preview:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install flask gunicorn
      - run:
          name: Start Flask app
          command: gunicorn app:app --bind 0.0.0.0:$PORT &
      - run:
          name: Wait for Flask server to start
          command: sleep 10

  newman-test:
    docker:
      - image: postman/newman:alpine
    steps:
      - checkout
      - run:
          name: Run Newman tests
          command: |
            newman run path/to/your/collection.json \
            --environment path/to/your/environment.json \
            --reporters cli

  security-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Run security tests
          command: echo "Running security tests..."

workflows:
  version: 2

  deploy-and-test:
    jobs:
      - deploy-preview:
          filters:
            branches:
              only: development

      - newman-test:
          requires:
            - deploy-preview
          filters:
            branches:
              only: development

  security-testing:
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - security-test

  manual-approval-workflow:
    jobs:
      - hold:
          type: approval
      - security-test:
          requires:
            - hold
